version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - run: python --version
      - run: pip install requests
      - setup_remote_docker:
          version: 20.10.18
      - run: echo << pipeline.trigger_source >>
      - when:
          # Sheduled builds only incrementally publish new images
          condition: 
            equal: ["scheduled_pipeline", << pipeline.trigger_source >>]
          steps:
           - run: echo "Generating scheduled config"
           - run: python scripts/generated_config.py -i 
      - when:
            # Pushing to a release branch force all images to be update to the lates version
          condition: 
            not:
              equal: ["scheduled_pipeline", << pipeline.trigger_source >>]
          steps:
            - run: echo "Generating forced config"
            - run: python scripts/generated_config.py
      - continuation/continue:
          configuration_path: /circleci/images.yml # use newly generated config to continue

workflows:
  setup_publish:
    triggers:
    - schedule:
        # Every day, 10am.
        cron: "0 10 * * *"
        filters:
          branches:
              only:
               - release\/.*
    jobs:
      - setup