version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2
  python: circleci/python@2.1.1

jobs:
  setup:
    docker:
      - image: cimg/python:3.12.1
    steps:
      - run: echo << pipeline.trigger_source >>
      - checkout
      - run: python --version
      - run: pip install requests pyyaml packaging
      - setup_remote_docker:
          version: 20.10.18
      - run: echo "Generating forced config"
      - run: python src/base/scripts/generate_config.py --is_incremental="scheduled_pipeline"!=<< pipeline.trigger_source >>  --trigger_branch=<< pipeline.git.branch >>
      - continuation/continue:
          configuration_path: .circleci/images.yml # use newly generated config to continue

workflows:
  setup_publish:
    jobs:
      - setup