version: 2.1

jobs:
  publish_image:
    docker:
      - image: cimg/base:stable
    parameters:
      godotVersion:
        type: string
      ubuntuVersion:
        type: string
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.18
      - run: echo $DOCKERHUB_PASSWORD | docker login -u flashlight13 --password-stdin
      - run: docker build --tag flashlight13/godot:<< parameters.godotVersion >> --build-arg ubuntuVersion=<< parameters.ubuntuVersion >> --build-arg godotVersion=<< parameters.godotVersion >> -f godot.dockerfile .
      - run: docker push flashlight13/godot:<< parameters.godotVersion >>

workflows:
  publish-workflow:
    jobs:
      - publish_image:
          godotVersion: "4.0"
          ubuntuVersion: "23.04"
          filters:
            branches:
                only:
                 - release
