version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@1.0.0

jobs:
  setup:
    docker:
      - image: cimg/python:3.12.1
    steps:
      - run: echo << pipeline.trigger_source >>
      - checkout
      - run: python --version
      - run: pip install requests pyyaml packaging networkx[default]
      - setup_remote_docker:
          version: docker23
      - run: echo "Generating forced config"
      - run: python src/generate_config.py --is_incremental="$[scheduled_pipeline==<< pipeline.trigger_source >>]"
      - continuation/continue:
          configuration_path: .circleci/images.yml # use newly generated config to continue

workflows:
  setup_publish:
    jobs:
      - setup