version: 2.1

jobs:
  publish_image:
    docker:
      - image: cimg/base:stable
    parameters:
      godotVersion:
        type: string
      ubuntuVersion:
        type: string
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.18
      - run: docker login -u flashlight13 -p $DOCKERHUB_PASSWORD
      - run: docker build --tag flashlight13/godot:<< parameters.godotVersion >> --build-arg ubuntuVersion=<< parameters.ubuntuVersion >> --build-arg godotVersion=<< parameters.godotVersion >> -f godot.dockerfile .
      - run: docker push flashlight13/godot:<< parameters.godotVersion >>

workflows:
  publish-workflow:
    jobs:
      - publish_image:
          godotVersion: "4.0.2"
          ubuntuVersion: "23.04"
    triggers:
        - schedule:
            cron: "0 0 * * *"
            filters:
              branches:
                only:
                 - release/*
