version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  publish_image:
    docker:
      - image: cimg/base:stable
    parameters:
      is_scheduled:
        description: true when the build is scheduled by the CI
        type: boolean
        default: false
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
      - when:
          condition: << parameters.is_scheduled >>
          steps:
            - run: python src/autoload.py --docker_login $DOCKERHUB_LOGIN --docker_pass $DOCKERHUB_PASSWORD -i 
      - when:
          condition: 
            not: << parameters.is_scheduled >>
          steps:
            - run: python src/autoload.py --docker_login $DOCKERHUB_LOGIN --docker_pass $DOCKERHUB_PASSWORD -d

workflows:
  publish-workflow:
    jobs:
      - publish_image:
          filters:
            branches:
                only:
                 - /release\/.*/