version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2
  python: circleci/python@2.1.1

jobs:
  setup:
    docker:
      - image: cimg/python:3.12.1
    steps:
      - run: echo << pipeline.trigger_source >>
      - checkout
      - run: python --version
      - run: pip install requests pyyaml packaging
      - setup_remote_docker:
          version: 20.10.18
      - when:
          # Sheduled builds only incrementally publish new images
          condition: 
            equal: ["scheduled_pipeline", << pipeline.trigger_source >>]
          steps:
           - run: echo "Generating scheduled config"
           - run: python base/scripts/generate_config.py -i --trigger_branch=<< pipeline.branch >>
      - when:
            # Pushing to a release branch force all images to be update to the lates version
          condition: 
            not:
              equal: ["scheduled_pipeline", << pipeline.trigger_source >>]
          steps:
            - run: echo "Generating forced config"
            - run: python base/scripts/generate_config.py --trigger_branch=<< pipeline.branch >>
      - continuation/continue:
          configuration_path: .circleci/images.yml # use newly generated config to continue

workflows:
  setup_publish:
    jobs:
      - setup