jobs:
  publish-4_2-rc1:
    docker:
    - image: cimg/base:stable
    steps:
    - checkout
    - setup_remote_docker:
        version: 20.10.18
    - run: echo DOCKER_PASSWORD | docker login - u DOCKER_LOGIN --password-stdin
    - run: docker build --tag flashlight13/godot:4.2-rc1 --build-arg ubuntuVersion=23.04
        --build-arg godotVersion=4.2 --build-arg engineUrl=https://github.com/godotengine/godot-builds/releases/download/4.2-rc1/Godot_v4.2-rc1_linux.x86_64.zip
        --build-arg engineArchiveName=Godot_v4.2-rc1_linux.x86_64.zip --build-arg
        engineFileName=Godot_v4.2-rc1_linux.x86_64 --build-arg templatesUrl=https://github.com/godotengine/godot-builds/releases/download/4.2-rc1/Godot_v4.2-rc1_export_templates.tpz
        --build-arg templatesArchiveName=Godot_v4.2-rc1_export_templates.tpz --build-arg
        templatesDirectory=4.2.rc1 -f images/godot.dockerfile .
    - run: docker push flashlight13/godot:4.2-rc1
  publish-4_2-rc2:
    docker:
    - image: cimg/base:stable
    steps:
    - checkout
    - setup_remote_docker:
        version: 20.10.18
    - run: echo DOCKER_PASSWORD | docker login - u DOCKER_LOGIN --password-stdin
    - run: docker build --tag flashlight13/godot:4.2-rc2 --build-arg ubuntuVersion=23.04
        --build-arg godotVersion=4.2 --build-arg engineUrl=https://github.com/godotengine/godot-builds/releases/download/4.2-rc2/Godot_v4.2-rc2_linux.x86_64.zip
        --build-arg engineArchiveName=Godot_v4.2-rc2_linux.x86_64.zip --build-arg
        engineFileName=Godot_v4.2-rc2_linux.x86_64 --build-arg templatesUrl=https://github.com/godotengine/godot-builds/releases/download/4.2-rc2/Godot_v4.2-rc2_export_templates.tpz
        --build-arg templatesArchiveName=Godot_v4.2-rc2_export_templates.tpz --build-arg
        templatesDirectory=4.2.rc2 -f images/godot.dockerfile .
    - run: docker push flashlight13/godot:4.2-rc2
  publish-4_2-stable:
    docker:
    - image: cimg/base:stable
    steps:
    - checkout
    - setup_remote_docker:
        version: 20.10.18
    - run: echo DOCKER_PASSWORD | docker login - u DOCKER_LOGIN --password-stdin
    - run: docker build --tag flashlight13/godot:4.2-stable --build-arg ubuntuVersion=23.04
        --build-arg godotVersion=4.2 --build-arg engineUrl=https://github.com/godotengine/godot-builds/releases/download/4.2-stable/Godot_v4.2-stable_linux.x86_64.zip
        --build-arg engineArchiveName=Godot_v4.2-stable_linux.x86_64.zip --build-arg
        engineFileName=Godot_v4.2-stable_linux.x86_64 --build-arg templatesUrl=https://github.com/godotengine/godot-builds/releases/download/4.2-stable/Godot_v4.2-stable_export_templates.tpz
        --build-arg templatesArchiveName=Godot_v4.2-stable_export_templates.tpz --build-arg
        templatesDirectory=4.2.stable -f images/godot.dockerfile .
    - run: docker push flashlight13/godot:4.2-stable
  publish-4_2_1-rc1:
    docker:
    - image: cimg/base:stable
    steps:
    - checkout
    - setup_remote_docker:
        version: 20.10.18
    - run: echo DOCKER_PASSWORD | docker login - u DOCKER_LOGIN --password-stdin
    - run: docker build --tag flashlight13/godot:4.2.1-rc1 --build-arg ubuntuVersion=23.04
        --build-arg godotVersion=4.2.1 --build-arg engineUrl=https://github.com/godotengine/godot-builds/releases/download/4.2.1-rc1/Godot_v4.2.1-rc1_linux.x86_64.zip
        --build-arg engineArchiveName=Godot_v4.2.1-rc1_linux.x86_64.zip --build-arg
        engineFileName=Godot_v4.2.1-rc1_linux.x86_64 --build-arg templatesUrl=https://github.com/godotengine/godot-builds/releases/download/4.2.1-rc1/Godot_v4.2.1-rc1_export_templates.tpz
        --build-arg templatesArchiveName=Godot_v4.2.1-rc1_export_templates.tpz --build-arg
        templatesDirectory=4.2.1.rc1 -f images/godot.dockerfile .
    - run: docker push flashlight13/godot:4.2.1-rc1
  publish-4_2_1-stable:
    docker:
    - image: cimg/base:stable
    steps:
    - checkout
    - setup_remote_docker:
        version: 20.10.18
    - run: echo DOCKER_PASSWORD | docker login - u DOCKER_LOGIN --password-stdin
    - run: docker build --tag flashlight13/godot:4.2.1-stable --build-arg ubuntuVersion=23.04
        --build-arg godotVersion=4.2.1 --build-arg engineUrl=https://github.com/godotengine/godot-builds/releases/download/4.2.1-stable/Godot_v4.2.1-stable_linux.x86_64.zip
        --build-arg engineArchiveName=Godot_v4.2.1-stable_linux.x86_64.zip --build-arg
        engineFileName=Godot_v4.2.1-stable_linux.x86_64 --build-arg templatesUrl=https://github.com/godotengine/godot-builds/releases/download/4.2.1-stable/Godot_v4.2.1-stable_export_templates.tpz
        --build-arg templatesArchiveName=Godot_v4.2.1-stable_export_templates.tpz
        --build-arg templatesDirectory=4.2.1.stable -f images/godot.dockerfile .
    - run: docker push flashlight13/godot:4.2.1-stable
version: 2.1
workflows:
  publish:
    jobs:
    - publish-4_2_1-stable
    - publish-4_2_1-rc1
    - publish-4_2-stable
    - publish-4_2-rc2
    - publish-4_2-rc1
