#!/bin/bash

Help()
{
  echo "$(basename "$0") [-h] [-s n] -- program to calculate the answer to life, the universe and everything

where:
  -h --help            show help
  (m)  --projectPath            path to project.godot
  (m)  --outputPath             uild output directory. Relative to --projectPath
       --artifactPath           path to the archive generated by the script. Relative to --projectPath
                                defaults to the same value as outputPath
       --artifactFileName       name of the archive to be generated by the script
                                defaults to index
  (m)  --buildPreset            name of the preset to use from export_presets.cfg
  (m)  --doubleImport           perform double import to work around 
                                https://github.com/godotengine/godot/issues/69511 for older Godot versions. 
                                Defaults to false
       --butlerPushDestination  destination for butler push command
       --butlerParams           these parameters are passed to the Butler

  (m)  means that the parameter is mandatory.
  "
}

DOUBLE_IMPORT=false

# Parse arguments
while (( "$#" )); do
  case "$1" in
    -h|--help)
      Help
      exit
      ;;
    -v)
      echo "Always the best! :)"
      exit
      ;;
    --projectPath)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        PROJECT_PATH=$2
        shift 2
      else
        echo "Error: Argument for $1 is missing" >&2
        exit 1
      fi
      ;;
    --outputPath)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        OUTPUT_PATH=$2
        shift 2
      else
        echo "Error: Argument for $1 is missing" >&2
        exit 1
      fi
      ;;
    --buildPreset)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        BUILD_PRESET=$2
        shift 2
      else
        echo "Error: Argument for $1 is missing" >&2
        exit 1
      fi
      ;;
    --doubleImport)
      DOUBLE_IMPORT=true
      shift 1
      ;;
    --artifactPath)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        ARTIFACT_PATH=$2
        shift 2
      else
        echo "Error: Argument for $1 is missing" >&2
        exit 1
      fi
      ;;
    --artifactFileName)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        ARTIFACT_FILE_NAME=$2
        shift 2
      else
        echo "Error: Argument for $1 is missing" >&2
        exit 1
      fi
      ;;
    --butlerPushDestination)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        BUTLER_PUSH_DESTINATION=$2
        shift 2
      else
        echo "Error: Argument for $1 is missing" >&2
        exit 1
      fi
      ;;
    --butlerParams)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        BUTLER_PARAMETERS=$2
        shift 2
      else
        echo "Error: Argument for $1 is missing" >&2
        exit 1
      fi
      ;;
    *)
      BUTLER_PARAMS="$BUTLER_PARAMS $1"
      shift
      ;;
  esac
done
shift $((OPTIND - 1))

echo "projectPath=$PROJECT_PATH"
echo "outputPath=$OUTPUT_PATH"
echo "buildPreset=$BUILD_PRESET"
echo "butlerPushDestination=$BUTLER_PUSH_DESTINATION"
echo "doubleImport=$DOUBLE_IMPORT"

if [ -z "$PROJECT_PATH" ] || [ -z "$OUTPUT_PATH" ] || [ -z "$BUILD_PRESET" ] || [ -z "$BUTLER_PUSH_DESTINATION" ] ; then
    echo "One or more parameter is missing"
    exit 1
fi
if [ -z "$ARTIFACT_PATH" ]; then
  ARTIFACT_PATH=$OUTPUT_PATH
fi
if [ -z "$ARTIFACT_FILE_NAME" ]; then
  ARTIFACT_FILE_NAME="index"
fi

# Export the project
cd $PROJECT_PATH
mkdir -p $OUTPUT_PATH
godot --headless --export-release "$BUILD_PRESET" "$OUTPUT_PATH/index.html"
echo "BUILD FINISHED"
if [ "$DOUBLE_IMPORT" = true ] ; then
    echo "STARTING SECOND WORKAROUND EXPORT"
    godot --headless --export-release "$BUILD_PRESET" "$OUTPUT_PATH/index.html"
fi

echo "PUSHING THE BUILD"
# Prepare the archive
mkdir -p $ARTIFACT_PATH
zip -rj $ARTIFACT_PATH/$ARTIFACT_FILE_NAME.zip $OUTPUT_PATH/

# Upload
butler push $ARTIFACT_PATH/$ARTIFACT_FILE_NAME.zip $BUTLER_PUSH_DESTINATION $BUTLER_PARAMS